# bullet
# ======

src_dir=$1
ins_dir=$2
cd src/${src_dir}

CC=clang CXXFLAGS="-fvisibility=hidden -fvisibility-inlines-hidden" cmake -DCMAKE_OSX_ARCHITECTURES:STRING="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING="10.10" -DCMAKE_OSX_SYSROOT:PATH=macosx10.12 -DCMAKE_INSTALL_PREFIX:PATH="${ins_dir}" -DBUILD_DEMOS:BOOL=OFF -DBUILD_BULLET2_DEMOS:BOOL=OFF -DBUILD_BULLET3:BOOL=OFF -DBUILD_CPU_DEMOS:BOOL=OFF -DBUILD_EXTRAS:BOOL=OFF -DBUILD_OPENGL3_DEMOS:BOOL=OFF -DBUILD_UNIT_TESTS:BOOL=OFF
make -j 4 && make install
cd ..
