# OpenCV
# ======n

src_dir=$1
ins_dir=$2
cd src/${src_dir}

mkdir -p build
cd build
CC="clang" cmake .. -DBUILD_DOCS:BOOL=OFF -DBUILD_PERF_TESTS:BOOL=OFF \
-DBUILD_TESTS:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=Release \
-DCMAKE_INSTALL_PREFIX:PATH="${ins_dir}" -DCMAKE_OSX_ARCHITECTURES:STRING="x86_64" \
-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_OSX_SYSROOT:PATH=macosx10.12 \
-DEIGEN_INCLUDE_PATH:PATH="${EIGEN_PATH}" \
-DWITH_CUDA:BOOL=OFF -DWITH_QT:BOOL=OFF -DWITH_WEBP:BOOL=OFF -DWITH_OPENCL:BOOL=OFF \
-DWITH_MATLAB:BOOL=OFF -DENABLE_SSE41:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF
make && make install
